# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61cb7b0ed828d085eee7b05934efbf428ce5353945e5105e5c1ba7c3a16f61caf8fae39b19122b91f0bb5d81d695830454cc8e584d950af379931e3666153807

test:
  secret_key_base: 6c1d93e150e9703ab82da4643479079c2027b37caeef80037c9fca39f58d5e7e47d2a2b42a35884fc7f210ebd7b2d2b1ae04e5864c4ae4adf43356d568c39b7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
